USE master;
GO
CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'QR6KJNY)!ZQsVQ$K';
go
CREATE CERTIFICATE MyServerCert WITH SUBJECT = 'My DEK Certificate';
go
USE AdventureWorks2019;
GO
CREATE DATABASE ENCRYPTION KEY
WITH ALGORITHM = AES_256
ENCRYPTION BY SERVER CERTIFICATE MyServerCert;
GO
ALTER DATABASE AdventureWorks2019
SET ENCRYPTION ON;
GO


ALTER DATABASE AdventureWorks2019 SET ENCRYPTION OFF;


